version: '3.8'

services:
  # Guacamole Database
  guacdb:
    container_name: guacdb
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: orizon_guacamole_root_password
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: orizon_guacamole_db_password
    volumes:
      - guacdb_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    networks:
      - guacnet

  # Guacamole Daemon
  guacd:
    container_name: guacd
    image: guacamole/guacd:latest
    restart: always
    networks:
      - guacnet

  # Guacamole Web Application
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guacdb
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: orizon_guacamole_db_password
    depends_on:
      - guacdb
      - guacd
    networks:
      - guacnet

networks:
  guacnet:
    driver: bridge

volumes:
  guacdb_data:
